dashboard: 'K8s pod health'
priority: 2

templating:
  variables:
    pod:
      label: 'Pod name'
      type: metric_label_values
      options:
        series_selector: 'container_memory_working_set_bytes'
        label: 'pod'

panel_groups:
- group: CPU metrics
  panels:
  - title: "CPU usage"
    type: "line-chart"
    y_label: "Cores per pod"
    metrics:
    - id: pod_cpu_usage_seconds_total
      query_range: 'rate(container_cpu_usage_seconds_total{pod="{{pod}}",container="POD"}[5m])'
      unit: "cores"
      label: pod
- group: Memory metrics
  panels:
  - title: "Memory usage working set"
    type: "line-chart"
    y_label: "Working set memory (MiB)"
    metrics:
    - id: pod_memory_working_set
      query_range: 'container_memory_working_set_bytes{pod="{{pod}}",container="POD"}/1024/1024'
      unit: "MiB"
      label: pod
- group: Network metrics
  panels:
  - title: "Network Receive (In)"
    type: "line-chart"
    y_label: "Received (KiB/sec)"
    metrics:
    - id: pod_network_receive
      query_range: 'rate(container_network_receive_bytes_total{pod="{{pod}}",container="POD"}[5m])/1024'
      unit: "KiB / sec"
      label: pod
  - title: "Network Transmit (Out)"
    type: "line-chart"
    y_label: "Transmitted (KiB/sec)"
    metrics:
    - id: pod_network_transmit
      query_range: 'rate(container_network_transmit_bytes_total{pod="{{pod}}",container="POD"}[5m])/1024'
      unit: "KiB / sec"
      label: pod
- group: Disk metrics
  panels:
  - title: "Disk Reads"
    type: "line-chart"
    y_label: "Disk reads (KiB/sec)"
    metrics:
    - id: pod_disk_reads
      query_range: 'rate(container_fs_reads_bytes_total{container="POD",pod="{{pod}}"}[5m])/1024'
      unit: "KiB / sec"
      label: pod
  - title: "Disk Writes"
    type: "line-chart"
    y_label: "Disk writes (KiB/sec)"
    metrics:
    - id: pod_disk_writes
      query_range: 'rate(container_fs_writes_bytes_total{container="POD",pod="{{pod}}"}[5m])/1024'
      unit: "KiB / sec"
      label: pod
