.default-tags:
  tags:
    - gitlab-org

.default-retry:
  retry:
    max: 2  # This is confusing but this means "3 runs at max".
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure

.default-before_script:
  before_script:
    - date
    - export GOPATH=$CI_PROJECT_DIR/.go
    - mkdir -p $GOPATH
    - source scripts/utils.sh
    - source scripts/prepare_build.sh
    - date

# Jobs that only need to pull cache
.default-cache:
  cache:
    key: "debian-stretch-ruby-2.6.3-node-12.x"
    paths:
      - .go/pkg/mod
      - vendor/ruby
      - .yarn-cache/
      - vendor/gitaly-ruby
    policy: pull

.if-master-stable-deploy-security-tag: &if-master-stable-deploy-security-tag
  if: '$CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME =~ /^[\d-]+-stable(-ee)?$/ || $CI_COMMIT_REF_NAME =~ /^\d+-\d+-auto-deploy-\d+$/ || $CI_COMMIT_REF_NAME =~ /^security\// || $CI_COMMIT_TAG'

.if-master-stable-deploy-security-tag-ee: &if-master-stable-deploy-security-tag-ee
  if: '($CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME =~ /^[\d-]+-stable(-ee)?$/ || $CI_COMMIT_REF_NAME =~ /^\d+-\d+-auto-deploy-\d+$/ || $CI_COMMIT_REF_NAME =~ /^security\// || $CI_COMMIT_TAG) && ($CI_PROJECT_NAME == "gitlab" || $CI_PROJECT_NAME == "gitlab-ee")'

.if-master-stable-deploy-security-tag-foss: &if-master-stable-deploy-security-tag-foss
  if: '($CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME =~ /^[\d-]+-stable(-ee)?$/ || $CI_COMMIT_REF_NAME =~ /^\d+-\d+-auto-deploy-\d+$/ || $CI_COMMIT_REF_NAME =~ /^security\// || $CI_COMMIT_TAG) && ($CI_PROJECT_NAME == "gitlab-foss" || $CI_PROJECT_NAME == "gitlab-ce" || $CI_PROJECT_NAME == "gitlabhq")'

.if-merge_request: &if-merge_request
  if: '$CI_MERGE_REQUEST_IID'

.if-merge_request-ee: &if-merge_request-ee
  if: '$CI_MERGE_REQUEST_IID && ($CI_PROJECT_NAME == "gitlab" || $CI_PROJECT_NAME == "gitlab-ee")'

.if-master: &if-master
  if: '$CI_COMMIT_REF_NAME == "master"'

.if-master-ee: &if-master-ee
  if: '$CI_COMMIT_REF_NAME == "master" && ($CI_PROJECT_NAME == "gitlab" || $CI_PROJECT_NAME == "gitlab-ee")'

.if-canonical-dot-com-master: &if-canonical-dot-com-master
  if: '$CI_COMMIT_REF_NAME == "master" && $CI_SERVER_HOST == "gitlab.com" && $CI_PROJECT_NAMESPACE =~ /^gitlab-org($|\/)/'

.if-canonical-dot-com-tag: &if-canonical-dot-com-tag
  if: '$CI_COMMIT_TAG && $CI_SERVER_HOST == "gitlab.com" && $CI_PROJECT_NAMESPACE =~ /^gitlab-org($|\/)/'

.if-canonical-dot-com-master-tag: &if-canonical-dot-com-master-tag
  if: '$CI_SERVER_HOST == "gitlab.com" && $CI_PROJECT_NAMESPACE =~ /^gitlab-org($|\/)/ && ($CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_TAG)'

.if-canonical-dot-com-merge_request: &if-canonical-dot-com-merge_request
  if: '$CI_MERGE_REQUEST_IID && $CI_SERVER_HOST == "gitlab.com" && $CI_PROJECT_NAMESPACE =~ /^gitlab-org($|\/)/'

.if-canonical-dot-com-schedule: &if-canonical-dot-com-schedule
  if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_SERVER_HOST == "gitlab.com" && $CI_PROJECT_NAMESPACE =~ /^gitlab-org($|\/)/'

.if-canonical-dot-com-master-stable-security-tag: &if-canonical-dot-com-master-stable-security-tag
  if: '$CI_SERVER_HOST == "gitlab.com" && $CI_PROJECT_NAMESPACE =~ /^gitlab-org($|\/)/ && $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME =~ /^[\d-]+-stable(-ee)?$/ || $CI_COMMIT_REF_NAME =~ /^security\// || $CI_COMMIT_TAG'

.rules-master-stable-deploy-security-tag: &rules-master-stable-deploy-security-tag
  <<: *if-master-stable-deploy-security-tag
  when: on_success

.rules-master-stable-deploy-security-tag-ee: &rules-master-stable-deploy-security-tag-ee
  <<: *if-master-stable-deploy-security-tag-ee
  when: on_success

.rules-canonical-dot-com-master-stable-security-tag: &rules-canonical-dot-com-master-stable-security-tag
  <<: *if-canonical-dot-com-master-stable-security-tag
  when: on_success

.default-only:
  only:
    refs:
      - master
      - /^[\d-]+-stable(-ee)?$/
      - /^\d+-\d+-auto-deploy-\d+$/
      - /^security\//
      - merge_requests
      - tags

.only:variables-canonical-dot-com:
  only:
    variables:
      - $CI_SERVER_HOST == "gitlab.com" && $CI_PROJECT_NAMESPACE =~ /^gitlab-org($|\/)/  # Matches the gitlab-org group or its subgroups

.only:variables_refs-canonical-dot-com-schedules:
  extends: .only:variables-canonical-dot-com
  only:
    refs:
      - schedules

.except:refs-deploy:
  except:
    refs:
      - /^\d+-\d+-auto-deploy-\d+$/

.except:refs-master-tags-stable-deploy:
  except:
    refs:
      - master
      - tags
      - /^[\d-]+-stable(-ee)?$/
      - /^\d+-\d+-auto-deploy-\d+$/

.only:kubernetes:
  only:
    kubernetes: active

.only-review:
  extends:
    - .only:variables-canonical-dot-com
    - .only:kubernetes
    - .except:refs-master-tags-stable-deploy

.only-review-schedules:
  extends:
    - .only:variables_refs-canonical-dot-com-schedules
    - .only:kubernetes
    - .except:refs-deploy

.code-patterns: &code-patterns
  - ".gitlab/ci/**/*"
  - ".{eslintignore,gitattributes,nvmrc,prettierrc,stylelintrc,yamllint}"
  - ".{codeclimate,eslintrc,gitlab-ci,haml-lint,haml-lint_todo,rubocop,rubocop_todo,scss-lint}.yml"
  - ".csscomb.json"
  - "Dockerfile.assets"
  - "*_VERSION"
  - "Gemfile{,.lock}"
  - "Rakefile"
  - "{babel.config,jest.config}.js"
  - "config.ru"
  - "{package.json,yarn.lock}"
  - "{,ee/}{app,bin,config,db,haml_lint,lib,locale,public,scripts,symbol,vendor}/**/*"
  - "doc/api/graphql/reference/*" # Files in this folder are auto-generated

.backstage-patterns: &backstage-patterns
  - "Dangerfile"
  - "danger/**/*"
  - "{,ee/}fixtures/**/*"
  - "{,ee/}rubocop/**/*"
  - "{,ee/}spec/**/*"
  - "doc/README.md"  # Some RSpec test rely on this file

.qa-patterns: &qa-patterns
  - ".dockerignore"
  - "qa/**/*"

.docs-patterns: &docs-patterns
  - ".gitlab/route-map.yml"
  - "doc/**/*"
  - ".markdownlint.json"

.graphql-patterns: &graphql-patterns
  - "{,ee/}app/graphql/**/*"
  - "{,ee/}lib/gitlab/graphql/**/*"

.code-backstage-patterns: &code-backstage-patterns
  - ".gitlab/ci/**/*"
  - ".{eslintignore,gitattributes,nvmrc,prettierrc,stylelintrc,yamllint}"
  - ".{codeclimate,eslintrc,gitlab-ci,haml-lint,haml-lint_todo,rubocop,rubocop_todo,scss-lint}.yml"
  - ".csscomb.json"
  - "Dockerfile.assets"
  - "*_VERSION"
  - "Gemfile{,.lock}"
  - "Rakefile"
  - "{babel.config,jest.config}.js"
  - "config.ru"
  - "{package.json,yarn.lock}"
  - "{,ee/}{app,bin,config,db,haml_lint,lib,locale,public,scripts,symbol,vendor}/**/*"
  # Backstage changes
  - "Dangerfile"
  - "danger/**/*"
  - "{,ee/}fixtures/**/*"
  - "{,ee/}rubocop/**/*"
  - "{,ee/}spec/**/*"
  - "doc/README.md"  # Some RSpec test rely on this file

.code-qa-patterns: &code-qa-patterns
  - ".gitlab/ci/**/*"
  - ".{eslintignore,gitattributes,nvmrc,prettierrc,stylelintrc,yamllint}"
  - ".{codeclimate,eslintrc,gitlab-ci,haml-lint,haml-lint_todo,rubocop,rubocop_todo,scss-lint}.yml"
  - ".csscomb.json"
  - "Dockerfile.assets"
  - "*_VERSION"
  - "Gemfile{,.lock}"
  - "Rakefile"
  - "{babel.config,jest.config}.js"
  - "config.ru"
  - "{package.json,yarn.lock}"
  - "{,ee/}{app,bin,config,db,haml_lint,lib,locale,public,scripts,symbol,vendor}/**/*"
  # QA changes
  - ".dockerignore"
  - "qa/**/*"

.code-backstage-qa-patterns: &code-backstage-qa-patterns
  - ".gitlab/ci/**/*"
  - ".{eslintignore,gitattributes,nvmrc,prettierrc,stylelintrc,yamllint}"
  - ".{codeclimate,eslintrc,gitlab-ci,haml-lint,haml-lint_todo,rubocop,rubocop_todo,scss-lint}.yml"
  - ".csscomb.json"
  - "Dockerfile.assets"
  - "*_VERSION"
  - "Gemfile{,.lock}"
  - "Rakefile"
  - "{babel.config,jest.config}.js"
  - "config.ru"
  - "{package.json,yarn.lock}"
  - "{,ee/}{app,bin,config,db,haml_lint,lib,locale,public,scripts,symbol,vendor}/**/*"
  # Backstage changes
  - "Dangerfile"
  - "danger/**/*"
  - "{,ee/}fixtures/**/*"
  - "{,ee/}rubocop/**/*"
  - "{,ee/}spec/**/*"
  - "doc/README.md"  # Some RSpec test rely on this file
  # QA changes
  - ".dockerignore"
  - "qa/**/*"

.use-pg9:
  services:
    - name: postgres:9.6
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:alpine

.use-pg10:
  image: "registry.gitlab.com/gitlab-org/gitlab-build-images:ruby-2.6.3-golang-1.11-git-2.22-chrome-73.0-node-12.x-yarn-1.16-postgresql-10-graphicsmagick-1.3.33"
  services:
    - name: postgres:10.9
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:alpine

.use-pg9-ee:
  services:
    - name: postgres:9.6
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:alpine
    - name: docker.elastic.co/elasticsearch/elasticsearch:5.6.12

.use-pg10-ee:
  image: "registry.gitlab.com/gitlab-org/gitlab-build-images:ruby-2.6.3-golang-1.11-git-2.22-chrome-73.0-node-12.x-yarn-1.16-postgresql-10-graphicsmagick-1.3.33"
  services:
    - name: postgres:10.9
      command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    - name: redis:alpine
    - name: docker.elastic.co/elasticsearch/elasticsearch:5.6.12

.as-if-foss:
  variables:
    FOSS_ONLY: '1'
