pages:
  extends:
    - .default-tags
    - .default-retry
    - .default-cache
  only:
    refs:
      - master
  stage: pages
  rules:
    - <<: *if-canonical-dot-com-master
      when: on_success
  dependencies: ["coverage", "karma", "gitlab:assets:compile pull-cache"]
  script:
    - mv public/ .public/
    - mkdir public/
    - mv coverage/ public/coverage-ruby/ || true
    - mv coverage-javascript/ public/coverage-javascript/ || true
    - mv webpack-report/ public/webpack-report/ || true
    - cp .public/assets/application-*.css public/application.css || true
    - cp .public/assets/application-*.css.gz public/application.css.gz || true
  artifacts:
    paths:
      - public
