.qa-job-base:
  extends:
    - .default-tags
    - .default-retry
  stage: test
  rules:
    - <<: *rules-master-stable-deploy-security-tag
    - <<: *if-merge_request
      changes: *code-qa-patterns
      when: on_success
  dependencies: []
  cache:
    key: "qa-framework-jobs:v1"
    paths:
      - vendor/ruby
  before_script:
    - cd qa/
    - bundle install --clean --jobs=$(nproc) --path=vendor --retry=3 --quiet
    - bundle check

qa:internal:
  extends: .qa-job-base
  script:
    - bundle exec rspec

qa:selectors:
  extends: .qa-job-base
  script:
    - bundle exec bin/qa Test::Sanity::Selectors

qa:selectors-foss:
  extends:
    - qa:selectors
    - .as-if-foss
  rules:
    - <<: *rules-master-stable-deploy-security-tag-ee
    - <<: *if-merge_request-ee
      changes: *code-qa-patterns
      when: on_success

.package-and-qa-base:
  image: ruby:2.6-alpine
  stage: qa
  dependencies: []
  retry: 0
  script:
    - source scripts/utils.sh
    - install_gitlab_gem
    - ./scripts/trigger-build omnibus

package-and-qa:
  extends:
    - .package-and-qa-base
    - .only:variables-canonical-dot-com
  rules:
    - <<: *if-canonical-dot-com-merge_request
      changes: *code-patterns
      when: manual
    - <<: *if-canonical-dot-com-merge_request
      changes: *code-qa-patterns
      when: on_success
  needs: ["build-qa-image", "gitlab:assets:compile pull-cache"]

schedule:package-and-qa:
  extends: .package-and-qa-base
  rules:
    - <<: *if-canonical-dot-com-schedule
      when: on_success
  needs: ["build-qa-image", "gitlab:assets:compile pull-cache"]
  allow_failure: true
