.package-and-qa-base:
  image: ruby:2.6-alpine
  stage: qa
  dependencies: []
  variables:
    GIT_DEPTH: "1"
  retry: 0
  script:
    - source scripts/utils.sh
    - install_gitlab_gem
    - ./scripts/trigger-build omnibus
  only:
    - branches@gitlab-org/gitlab-ce
    - branches@gitlab-org/gitlab-ee
  except:
    - master

package-and-qa-manual:
  extends:
    - .package-and-qa-base
    - .except-docs-qa
  except:
    refs:
      - master
  needs: ["build-qa-image", "gitlab:assets:compile pull-cache"]
  when: manual

package-and-qa-manual:master:
  extends:
    - .package-and-qa-base
  needs: ["build-qa-image", "gitlab:assets:compile"]
  only:
    refs:
      - master
  when: manual

package-and-qa:
  extends: .package-and-qa-base
  needs: ["build-qa-image", "gitlab:assets:compile pull-cache"]
  allow_failure: true
  only:
    - /(^qa[\/-].*|.*-qa$)/@gitlab-org/gitlab-ce
    - /(^qa[\/-].*|.*-qa$)/@gitlab-org/gitlab-ee
