---

# Syncs any changes pushed to a stable branch to the corresponding CE stable
# branch. We run this prior to any tests so that random failures don't prevent a
# sync.
sync-stable-branch:
  # We don't need/want any global before/after commands, so we overwrite these
  # settings.
  image: alpine:edge
  stage: sync
  # This job should only run on EE stable branches on the canonical GitLab.com
  # repository.
  rules:
    - if: '$CI_SERVER_HOST == "gitlab.com" && $CI_PROJECT_PATH == "gitlab-org/gitlab" && $CI_COMMIT_REF_NAME =~ /^[\d-]+-stable-ee$/'
  before_script:
    - apk add --no-cache --update curl bash
  after_script: []
  script:
    - bash scripts/sync-stable-branch.sh
