# Insurance in case a gem needed by one of our releases gets yanked from
# rubygems.org in the future.
cache gems:
  extends:
    - .default-tags
    - .default-retry
    - .default-cache
    - .default-before_script
  stage: test
  rules:
    - <<: *if-canonical-dot-com-master-tag
      when: on_success
  dependencies: ["setup-test-env"]
  needs: ["setup-test-env"]
  variables:
    SETUP_DB: "false"
  script:
    - bundle package --all --all-platforms
  artifacts:
    paths:
      - vendor/cache
  only:
    refs:
      - master
      - tags

.minimal-job:
  extends:
    - .default-tags
    - .default-retry
  rules:
    - <<: *if-master-stable-deploy-security-tag
      when: on_success
    - <<: *if-merge_request
      changes: *code-backstage-patterns
      when: on_success
  dependencies: []

gitlab_git_test:
  extends: .minimal-job
  script:
    - spec/support/prepare-gitlab-git-test-for-commit --check-for-changes

no_ee_check:
  extends: .minimal-job
  rules:
    - <<: *if-master-stable-deploy-security-tag-foss
      when: on_success
  script:
    - scripts/no-ee-check
